version: "3.0"

services:

  api:
    build:
      context: .
    image: moleculer-web-error-handling-middleware
    env_file: docker-compose.env
    volumes:
      - .:/app
    command: npm run dev
    environment:
      SERVICES: api
      PORT: 3000
      NODE_ENV: development
    labels:
      - "traefik.enable=true"
      - "traefik.backend=api"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"

  greeter:
    build:
      context: .
    image: moleculer-web-error-handling-middleware
    env_file: docker-compose.env
    environment:
      SERVICES: greeter


  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=INFO --docker.exposedbydefault=false
    ports:
      - "3000:80"
      - "3001:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
